version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visdat-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - visdat-network

networks:
  visdat-network:
    driver: bridge
